import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title="Valorant Style Sniper Range", layout="wide")
st.title("🎯 VALO-SNIPER: Tactical Aim Range")
st.caption("🎮 조작법: 마우스 드래그 = 시점 전환 | 클릭 = 스나이퍼 사격 | WASD = 지면 이동 (높이 고정)")

game_html = (
    "<!DOCTYPE html>\n"
    "<html lang=\"ko\">\n"
    "<head>\n"
    "    <meta charset=\"UTF-8\">\n"
    "    <style>\n"
    "        body { margin: 0; overflow: hidden; background-color: #0d1117; font-family: sans-serif; user-select: none; }\n"
    "        #crosshair {\n"
    "            position: absolute; top: 50%; left: 50%; width: 14px; height: 14px;\n"
    "            transform: translate(-50%, -50%); pointer-events: none; z-index: 10;\n"
    "        }\n"
    "        #crosshair::before, #crosshair::after {\n"
    "            content: ''; position: absolute; background: #00ffaa; box-shadow: 0 0 8px #00ffaa;\n"
    "        }\n"
    "        #crosshair::before { top: 6px; left: 0; width: 14px; height: 2px; }\n"
    "        #crosshair::after { top: 0; left: 6px; width: 2px; height: 14px; }\n"
    "        #hud {\n"
    "            position: absolute; top: 20px; left: 20px; color: #fff; font-size: 22px;\n"
    "            font-weight: 800; z-index: 10; letter-spacing: 1px;\n"
    "            background: rgba(15, 23, 42, 0.7); padding: 12px 20px; border-left: 4px solid #ff4655;\n"
    "        }\n"
    "        #hp-bar {\n"
    "            position: absolute; bottom: 30px; left: 50%; transform: translateX(-50%);\n"
    "            width: 300px; height: 12px; background: rgba(255,255,255,0.2); z-index: 10;\n"
    "            border: 1px solid #ff4655;\n"
    "        }\n"
    "        #hp-fill {\n"
    "            width: 100%; height: 100%; background: #00ffaa; transition: width 0.2s;\n"
    "        }\n"
    "        #game-over {\n"
    "            position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);\n"
    "            color: #ff4655; font-size: 48px; font-weight: 900; text-align: center; display: none; z-index: 20;\n"
    "            text-shadow: 0 0 20px rgba(255, 70, 85, 0.8);\n"
    "        }\n"
    "    </style>\n"
    "</head>\n"
    "<body>\n"
    "    <div id=\"crosshair\"></div>\n"
    "    <div id=\"hud\">ELIMINATED: <span id=\"score\" style=\"color:#ff4655;\">0</span></div>\n"
    "    <div id=\"hp-bar\"><div id=\"hp-fill\"></div></div>\n"
    "    <div id=\"game-over\">MISSION FAILED<br><span style=\"font-size:20px; color:#fff;\">클릭하여 재도전</span></div>\n"
    "\n"
    "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js\"></script>\n"
    "    <script src=\"https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js\"></script>\n"
    "\n"
    "    <script>\n"
    "        let scene = new THREE.Scene();\n"
    "        scene.background = new THREE.Color(0x0a0e14);\n"
    "        scene.fog = new THREE.FogExp2(0x0a0e14, 0.012);\n"
    "\n"
    "        let camera = new THREE.PerspectiveCamera(65, window.innerWidth / window.innerHeight, 0.1, 1000);\n"
    "        let renderer = new THREE.WebGLRenderer({ antialias: true });\n"
    "        renderer.setSize(window.innerWidth, window.innerHeight);\n"
    "        document.body.appendChild(renderer.domElement);\n"
    "\n"
    "        let controls = new THREE.OrbitControls(camera, renderer.domElement);\n"
    "        controls.enablePan = false;\n"
    "        controls.enableZoom = false;\n"
    "\n"
    "        const PLAYER_HEIGHT = 2.0;\n"
    "        camera.position.set(0, PLAYER_HEIGHT, 0.1);\n"
    "        controls.target.set(0, PLAYER_HEIGHT, -10);\n"
    "\n"
    "        // 발로란트풍 조명\n"
    "        scene.add(new THREE.AmbientLight(0xffffff, 0.5));\n"
    "        let dirLight = new THREE.DirectionalLight(0xff4655, 0.8);\n"
    "        dirLight.position.set(30, 50, 20);\n"
    "        scene.add(dirLight);\n"
    "\n"
    "        // 바닥 그리드\n"
    "        let grid = new THREE.GridHelper(200, 60, 0xff4655, 0x1e293b);\n"
    "        scene.add(grid);\n"
    "\n"
    "        // 스나이퍼 총기 모델링 (카메라 하단에 고정)\n"
    "        let sniperGroup = new THREE.Group();\n"
    "        let barrelGeo = new THREE.CylinderGeometry(0.04, 0.04, 2);\n"
    "        barrelGeo.rotateX(Math.PI / 2);\n"
    "        let gunMat = new THREE.MeshStandardMaterial({ color: 0x111827, roughness: 0.3 });\n"
    "        let barrel = new THREE.Mesh(barrelGeo, gunMat);\n"
    "        barrel.position.set(0, 0, -1);\n"
    "\n"
    "        let scopeGeo = new THREE.CylinderGeometry(0.08, 0.08, 0.6);\n"
    "        scopeGeo.rotateX(Math.PI / 2);\n"
    "        let scopeMat = new THREE.MeshStandardMaterial({ color: 0x00ffaa, emissive: 0x00ffaa, emissiveIntensity: 0.8 });\n"
    "        let scope = new THREE.Mesh(scopeGeo, scopeMat);\n"
    "        scope.position.set(0, 0.12, -0.6);\n"
    "\n"
    "        sniperGroup.add(barrel);\n"
    "        sniperGroup.add(scope);\n"
    "        sniperGroup.position.set(0.35, -0.35, -0.5);\n"
    "        camera.add(sniperGroup);\n"
    "        scene.add(camera);\n"
    "\n"
    "        // 플레이어 상태\n"
    "        let hp = 100;\n"
    "        let score = 0;\n"
    "        let isGameOver = false;\n"
    "        let moveForward = false, moveBackward = false, moveLeft = false, moveRight = false;\n"
    "\n"
    "        // 봇(Bot) 배열\n"
    "        let bots = [];\n"
    "\n"
    "        function createBot() {\n"
    "            if (isGameOver) return;\n"
    "            let botGroup = new THREE.Group();\n"
    "            \n"
    "            // 몸통 모델\n"
    "            let bodyGeo = new THREE.CylinderGeometry(0.5, 0.3, 1.8);\n"
    "            let bodyMat = new THREE.MeshStandardMaterial({ color: 0xff4655, emissive: 0xaa0022, emissiveIntensity: 0.5 });\n"
    "            let body = new THREE.Mesh(bodyGeo, bodyMat);\n"
    "            body.position.y = 0.9;\n"
    "\n"
    "            // 머리 모델\n"
    "            let headGeo = new THREE.SphereGeometry(0.35, 12, 12);\n"
    "            let headMat = new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: 0.3 });\n"
    "            let head = new THREE.Mesh(headGeo, headMat);\n"
    "            head.position.y = 2.0;\n"
    "\n"
    "            botGroup.add(body);\n"
    "            botGroup.add(head);\n"
    "\n"
    "            // 무작위 스폰 위치 (플레이어 주변)\n"
    "            let angle = Math.random() * Math.PI * 2;\n"
    "            let distance = 25 + Math.random() * 25;\n"
    "            botGroup.position.set(\n"
    "                camera.position.x + Math.cos(angle) * distance,\n"
    "                0,\n"
    "                camera.position.z + Math.sin(angle) * distance\n"
    "            );\n"
    "\n"
    "            scene.add(botGroup);\n"
    "            bots.push(botGroup);\n"
    "        }\n"
    "\n"
    "        // 시작 시 봇 5마리 생성\n"
    "        for (let i = 0; i < 5; i++) createBot();\n"
    "        setInterval(() => { if (bots.length < 8) createBot(); }, 2500);\n"
    "\n"
    "        // 키보드 조작 이벤트\n"
    "        document.addEventListener('keydown', (e) => {\n"
    "            switch (e.code) {\n"
    "                case 'KeyW': moveForward = true; break;\n"
    "                case 'KeyA': moveLeft = true; break;\n"
    "                case 'KeyS': moveBackward = true; break;\n"
    "                case 'KeyD': moveRight = true; break;\n"
    "            }\n"
    "        });\n"
    "        document.addEventListener('keyup', (e) => {\n"
    "            switch (e.code) {\n"
    "                case 'KeyW': moveForward = false; break;\n"
    "                case 'KeyA': moveLeft = false; break;\n"
    "                case 'KeyS': moveBackward = false; break;\n"
    "                case 'KeyD': moveRight = false; break;\n"
    "            }\n"
    "        });\n"
    "\n"
    "        // 사격 레이캐스터\n"
    "        let raycaster = new THREE.Raycaster();\n"
    "        let canShoot = true;\n"
    "\n"
    "        document.addEventListener('mousedown', (e) => {\n"
    "            if (isGameOver) {\n"
    "                resetGame();\n"
    "                return;\n"
    "            }\n"
    "            if (!canShoot) return;\n"
    "            canShoot = false;\n"
    "\n"
    "            // 스나이퍼 반동 모션\n"
    "            sniperGroup.position.z = -0.2;\n"
    "            sniperGroup.rotation.x = 0.2;\n"
    "            setTimeout(() => {\n"
    "                sniperGroup.position.z = -0.5;\n"
    "                sniperGroup.rotation.x = 0;\n"
    "                canShoot = true;\n"
    "            }, 600); // 스나이퍼 연사 속도 제어\n"
    "\n"
    "            raycaster.setFromCamera(new THREE.Vector2(0, 0), camera);\n"
    "            let targets = [];\n"
    "            bots.forEach(b => targets.push(...b.children));\n"
    "\n"
    "            let intersects = raycaster.intersectObjects(targets);\n"
    "            if (intersects.length > 0) {\n"
    "                let hitObj = intersects[0].object;\n"
    "                let hitBot = hitObj.parent;\n"
    "                scene.remove(hitBot);\n"
    "                bots = bots.filter(b => b !== hitBot);\n"
    "                score += 1;\n"
    "                document.getElementById('score').innerText = score;\n"
    "                setTimeout(createBot, 1000);\n"
    "            }\n"
    "        });\n"
    "\n"
    "        function resetGame() {\n"
    "            bots.forEach(b => scene.remove(b));\n"
    "            bots = [];\n"
    "            hp = 100;\n"
    "            score = 0;\n"
    "            isGameOver = false;\n"
    "            document.getElementById('hp-fill').style.width = '100%';\n"
    "            document.getElementById('score').innerText = '0';\n"
    "            document.getElementById('game-over').style.display = 'none';\n"
    "            camera.position.set(0, PLAYER_HEIGHT, 0.1);\n"
    "            controls.target.set(0, PLAYER_HEIGHT, -10);\n"
    "            for (let i = 0; i < 5; i++) createBot();\n"
    "        }\n"
    "\n"
    "        function animate() {\n"
    "            requestAnimationFrame(animate);\n"
    "            if (isGameOver) return;\n"
    "\n"
    "            let moveSpeed = 0.2;\n"
    "            let forward = new THREE.Vector3();\n"
    "            camera.getWorldDirection(forward);\n"
    "            forward.y = 0;\n"
    "            forward.normalize();\n"
    "\n"
    "            let right = new THREE.Vector3();\n"
    "            right.crossVectors(forward, new THREE.Vector3(0, 1, 0)).normalize();\n"
    "\n"
    "            let moveVector = new THREE.Vector3();\n"
    "            if (moveForward) moveVector.add(forward);\n"
    "            if (moveBackward) moveVector.sub(forward);\n"
    "            if (moveRight) moveVector.add(right);\n"
    "            if (moveLeft) moveVector.sub(right);\n"
    "\n"
    "            if (moveVector.lengthSq() > 0) {\n"
    "                moveVector.normalize().multiplyScalar(moveSpeed);\n"
    "                camera.position.add(moveVector);\n"
    "                controls.target.add(moveVector);\n"
    "            }\n"
    "\n"
    "            // Y축 높이 완전 고정\n"
    "            camera.position.y = PLAYER_HEIGHT;\n"
    "\n"
    "            // 봇 AI: 플레이어를 향해 천천히 이동 및 공격\n"
    "            bots.forEach(bot => {\n"
    "                let dir = new THREE.Vector3().subVectors(camera.position, bot.position);\n"
    "                dir.y = 0;\n"
    "                let dist = dir.length();\n"
    "                dir.normalize();\n"
    "\n"
    "                if (dist > 2.0) {\n"
    "                    bot.position.addScaledVector(dir, 0.05);\n"
    "                } else {\n"
    "                    // 근접 시 플레이어 공격\n"
    "                    hp -= 0.3;\n"
    "                    document.getElementById('hp-fill').style.width = Math.max(0, hp) + '%';\n"
    "                    if (hp <= 0) {\n"
    "                        isGameOver = true;\n"
    "                        document.getElementById('game-over').style.display = 'block';\n"
    "                    }\n"
    "                }\n"
    "                bot.lookAt(camera.position.x, 0, camera.position.z);\n"
    "            });\n"
    "\n"
    "            controls.update();\n"
    "            renderer.render(scene, camera);\n"
    "        }\n"
    "        animate();\n"
    "    </script>\n"
    "</body>\n"
    "</html>\n"
)

components.html(game_html, height=720)
