import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title="Valorant Roman Town Sniper", layout="wide")
st.title("🏛️ VALORANT: Roman Town Protocol")
st.caption("🎮 조작법: [화면 클릭] 포커스 | WASD = 이동 | 마우스 드래그 = 시점 전환 | 좌클릭 = 사격 | 우클릭 = 스나이퍼 조준(ADS)")

game_html = (
    "<!DOCTYPE html>\n"
    "<html lang=\"ko\">\n"
    "<head>\n"
    "    <meta charset=\"UTF-8\">\n"
    "    <style>\n"
    "        body { margin: 0; overflow: hidden; background-color: #dce8f0; font-family: 'Segoe UI', sans-serif; user-select: none; }\n"
    "        #crosshair {\n"
    "            position: absolute; top: 50%; left: 50%; width: 8px; height: 8px;\n"
    "            transform: translate(-50%, -50%); pointer-events: none; z-index: 10;\n"
    "            background: #ff4655; border-radius: 50%; box-shadow: 0 0 8px #ff4655;\n"
    "            transition: transform 0.1s;\n"
    "        }\n"
    "        #hud {\n"
    "            position: absolute; top: 20px; left: 20px; color: #1e293b; font-size: 20px;\n"
    "            font-weight: 800; z-index: 10; letter-spacing: 2px;\n"
    "            background: rgba(255, 255, 255, 0.85); padding: 12px 22px; border-left: 5px solid #ff4655;\n"
    "            box-shadow: 0 4px 15px rgba(0,0,0,0.15);\n"
    "        }\n"
    "        #hp-bar {\n"
    "            position: absolute; bottom: 30px; left: 50%; transform: translateX(-50%);\n"
    "            width: 320px; height: 14px; background: rgba(30, 41, 59, 0.7); z-index: 10;\n"
    "            border: 2px solid #ff4655; border-radius: 3px;\n"
    "        }\n"
    "        #hp-fill {\n"
    "            width: 100%; height: 100%; background: #00f5a0; transition: width 0.1s;\n"
    "        }\n"
    "        #game-over {\n"
    "            position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);\n"
    "            color: #ff4655; font-size: 42px; font-weight: 900; text-align: center; display: none; z-index: 20;\n"
    "            text-shadow: 0 0 20px rgba(255, 70, 85, 0.8); background: rgba(0,0,0,0.7); padding: 30px;\n"
    "        }\n"
    "        #focus-notice {\n"
    "            position: absolute; top: 75px; left: 20px; color: #1e293b; font-size: 13px; z-index: 10;\n"
    "            background: rgba(255,255,255,0.7); padding: 6px 12px; border-radius: 4px; font-weight: 600;\n"
    "        }\n"
    "    </style>\n"
    "</head>\n"
    "<body>\n"
    "    <div id=\"crosshair\"></div>\n"
    "    <div id=\"hud\">ELIMINATIONS: <span id=\"score\" style=\"color:#ff4655;\">0</span></div>\n"
    "    <div id=\"focus-notice\">💡 좌클릭 = 사격 | 우클릭 유지 = 저격 조준(ADS)</div>\n"
    "    <div id=\"hp-bar\"><div id=\"hp-fill\"></div></div>\n"
    "    <div id=\"game-over\">MISSION FAILED<br><span style=\"font-size:18px; color:#fff;\">클릭하여 다시 시작</span></div>\n"

    "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js\"></script>\n"
    "    <script src=\"https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js\"></script>\n"

    "    <script>\n"
    "        window.focus();\n"
    "        document.addEventListener('contextmenu', event => event.preventDefault()); // 우클릭 메뉴 방지\n"

    "        let scene = new THREE.Scene();\n"
    "        scene.background = new THREE.Color(0xdce8f0);\n"
    "        scene.fog = new THREE.FogExp2(0xdce8f0, 0.007);\n"

    "        let camera = new THREE.PerspectiveCamera(65, window.innerWidth / window.innerHeight, 0.1, 1000);\n"
    "        let renderer = new THREE.WebGLRenderer({ antialias: true });\n"
    "        renderer.setSize(window.innerWidth, window.innerHeight);\n"
    "        renderer.toneMapping = THREE.ACESFilmicToneMapping;\n"
    "        document.body.appendChild(renderer.domElement);\n"

    "        let controls = new THREE.OrbitControls(camera, renderer.domElement);\n"
    "        controls.enablePan = false;\n"
    "        controls.enableZoom = false;\n"

    "        const PLAYER_HEIGHT = 2.0;\n"
    "        camera.position.set(0, PLAYER_HEIGHT, 0.1);\n"
    "        controls.target.set(0, PLAYER_HEIGHT, -10);\n"

    "        // 조명\n"
    "        scene.add(new THREE.AmbientLight(0xfff8ed, 0.8));\n"
    "        let sun = new THREE.DirectionalLight(0xfffaed, 1.2);\n"
    "        sun.position.set(40, 60, 30);\n"
    "        scene.add(sun);\n"

    "        // 로마 건축물\n"
    "        let stoneMat = new THREE.MeshStandardMaterial({ color: 0xded3c1, roughness: 0.7 });\n"
    "        let roofMat = new THREE.MeshStandardMaterial({ color: 0xb85b35, roughness: 0.6 });\n"
    "        let groundMat = new THREE.MeshStandardMaterial({ color: 0xc2b299, roughness: 0.9 });\n"

    "        let floor = new THREE.Mesh(new THREE.PlaneGeometry(180, 180), groundMat);\n"
    "        floor.rotation.x = -Math.PI / 2;\n"
    "        scene.add(floor);\n"

    "        let grid = new THREE.GridHelper(180, 45, 0x8b7e66, 0xb0a38e);\n"
    "        grid.position.y = 0.01;\n"
    "        scene.add(grid);\n"

    "        function createColumn(x, z) {\n"
    "            let col = new THREE.Group();\n"
    "            let base = new THREE.Mesh(new THREE.BoxGeometry(1.6, 0.4, 1.6), stoneMat);\n"
    "            base.position.y = 0.2;\n"
    "            let shaft = new THREE.Mesh(new THREE.CylinderGeometry(0.5, 0.6, 6, 16), stoneMat);\n"
    "            shaft.position.y = 3.4;\n"
    "            let capital = new THREE.Mesh(new THREE.BoxGeometry(1.5, 0.5, 1.5), stoneMat);\n"
    "            capital.position.y = 6.65;\n"
    "            col.add(base, shaft, capital);\n"
    "            col.position.set(x, 0, z);\n"
    "            scene.add(col);\n"
    "        }\n"

    "        function createHouse(x, z, w, h, d) {\n"
    "            let bldg = new THREE.Group();\n"
    "            let wall = new THREE.Mesh(new THREE.BoxGeometry(w, h, d), stoneMat);\n"
    "            wall.position.y = h / 2;\n"
    "            let roof = new THREE.Mesh(new THREE.ConeGeometry(Math.max(w, d) * 0.75, 2.5, 4), roofMat);\n"
    "            roof.position.y = h + 1.25;\n"
    "            roof.rotation.y = Math.PI / 4;\n"
    "            bldg.add(wall, roof);\n"
    "            bldg.position.set(x, 0, z);\n"
    "            scene.add(bldg);\n"
    "        }\n"

    "        createHouse(-18, -25, 8, 6, 10);\n"
    "        createHouse(20, -30, 10, 7, 8);\n"
    "        createHouse(-22, 10, 9, 6, 9);\n"
    "        createHouse(22, 12, 8, 6, 8);\n"

    "        createColumn(-8, -12); createColumn(8, -12);\n"
    "        createColumn(-8, -22); createColumn(8, -22);\n"
    "        createColumn(-15, 0); createColumn(15, 0);\n"

    "        // -----------------------------------------------------\n"
    "        // 총기 및 스코프 조준 시스템\n"
    "        // -----------------------------------------------------\n"
    "        let gun = new THREE.Group();\n"
    "        let gunDark = new THREE.MeshStandardMaterial({ color: 0x1a1e24, roughness: 0.3, metalness: 0.7 });\n"
    "        let gunGold = new THREE.MeshStandardMaterial({ color: 0xc5a059, roughness: 0.2, metalness: 0.8 });\n"
    "        let scopeLensMat = new THREE.MeshStandardMaterial({ color: 0x00ffcc, emissive: 0x00aa88, emissiveIntensity: 0.6 });\n"

    "        let barrel = new THREE.Mesh(new THREE.CylinderGeometry(0.035, 0.045, 2.8, 12), gunDark);\n"
    "        barrel.rotateX(Math.PI / 2); barrel.position.set(0, 0, -1.3);\n"

    "        let muzzle = new THREE.Mesh(new THREE.BoxGeometry(0.09, 0.09, 0.25), gunGold);\n"
    "        muzzle.position.set(0, 0, -2.7);\n"

    "        let scopeTube = new THREE.Mesh(new THREE.CylinderGeometry(0.08, 0.08, 0.9, 16), gunDark);\n"
    "        scopeTube.rotateX(Math.PI / 2); scopeTube.position.set(0, 0.16, -0.6);\n"

    "        let scopeLens = new THREE.Mesh(new THREE.CylinderGeometry(0.075, 0.075, 0.02, 16), scopeLensMat);\n"
    "        scopeLens.rotateX(Math.PI / 2); scopeLens.position.set(0, 0.16, -1.05);\n"

    "        let receiver = new THREE.Mesh(new THREE.BoxGeometry(0.16, 0.22, 1.1), gunDark);\n"
    "        receiver.position.set(0, -0.04, -0.3);\n"

    "        let mag = new THREE.Mesh(new THREE.BoxGeometry(0.12, 0.4, 0.25), gunGold);\n"
    "        mag.position.set(0, -0.28, -0.4); mag.rotation.x = -0.2;\n"

    "        let stock = new THREE.Mesh(new THREE.BoxGeometry(0.12, 0.2, 0.7), gunDark);\n"
    "        stock.position.set(0, -0.02, 0.3);\n"

    "        gun.add(barrel, muzzle, scopeTube, scopeLens, receiver, mag, stock);\n"

    "        const NORMAL_GUN_POS = new THREE.Vector3(0.38, -0.32, -0.55);\n"
    "        const AIM_GUN_POS = new THREE.Vector3(0, -0.16, -0.4); // ADS 시 스코프가 화면 중앙으로 오도록\n"
    "        gun.position.copy(NORMAL_GUN_POS);\n"

    "        camera.add(gun);\n"
    "        scene.add(camera);\n"

    "        // -----------------------------------------------------\n"
    "        // 고디테일 차세대 전투 로봇 (Robot AI)\n"
    "        // -----------------------------------------------------\n"
    "        let hp = 100;\n"
    "        let score = 0;\n"
    "        let isGameOver = false;\n"
    "        let keys = { KeyW: false, KeyS: false, KeyA: false, KeyD: false };\n"
    "        let bots = [];\n"
    "        let isAiming = false;\n"

    "        function createBot() {\n"
    "            if (isGameOver) return;\n"
    "            let bot = new THREE.Group();\n"

    "            let armorMat = new THREE.MeshStandardMaterial({ color: 0x334155, roughness: 0.3, metalness: 0.7 });\n"
    "            let energyMat = new THREE.MeshStandardMaterial({ color: 0xff4655, emissive: 0xff1122, emissiveIntensity: 1.2 });\n"
    "            let jointMat = new THREE.MeshStandardMaterial({ color: 0x0f172a, roughness: 0.9, metalness: 0.2 });\n"
    "            let detailGold = new THREE.MeshStandardMaterial({ color: 0xd4af37, roughness: 0.3, metalness: 0.8 });\n"

    "            // 머리 & 센서 렌즈\n"
    "            let head = new THREE.Mesh(new THREE.BoxGeometry(0.4, 0.35, 0.4), armorMat);\n"
    "            head.position.y = 2.05;\n"
    "            let eyeLens = new THREE.Mesh(new THREE.CylinderGeometry(0.1, 0.1, 0.1, 12), energyMat);\n"
    "            eyeLens.rotateX(Math.PI / 2); eyeLens.position.set(0, 2.08, -0.21);\n"
    "            let headAntenna = new THREE.Mesh(new THREE.CylinderGeometry(0.02, 0.02, 0.3), detailGold);\n"
    "            headAntenna.position.set(0.15, 2.3, 0);\n"

    "            // 흉부 코어 & 반응로\n"
    "            let chest = new THREE.Mesh(new THREE.BoxGeometry(0.8, 0.85, 0.5), armorMat);\n"
    "            chest.position.y = 1.35;\n"
    "            let core = new THREE.Mesh(new THREE.OctahedronGeometry(0.18), energyMat);\n"
    "            core.position.set(0, 1.45, -0.26);\n"

    "            // 다층 어깨 장갑 (Pad Shoulder)\n"
    "            let shoulderL = new THREE.Mesh(new THREE.BoxGeometry(0.3, 0.3, 0.4), armorMat);\n"
    "            shoulderL.position.set(-0.55, 1.65, 0);\n"
    "            let shoulderR = new THREE.Mesh(new THREE.BoxGeometry(0.3, 0.3, 0.4), armorMat);\n"
    "            shoulderR.position.set(0.55, 1.65, 0);\n"

    "            // 관절 팔 & 머즐 패드\n"
    "            let armL = new THREE.Mesh(new THREE.CylinderGeometry(0.08, 0.08, 0.65), jointMat);\n"
    "            armL.position.set(-0.55, 1.15, 0);\n"
    "            let armR = new THREE.Mesh(new THREE.CylinderGeometry(0.08, 0.08, 0.65), jointMat);\n"
    "            armR.position.set(0.55, 1.15, 0);\n"

    "            // 골반 & 강화 다리 구조물\n"
    "            let waist = new THREE.Mesh(new THREE.CylinderGeometry(0.25, 0.25, 0.3), jointMat);\n"
    "            waist.position.y = 0.85;\n"
    "            let legL = new THREE.Mesh(new THREE.BoxGeometry(0.18, 0.7, 0.22), armorMat);\n"
    "            legL.position.set(-0.22, 0.4, 0);\n"
    "            let legR = new THREE.Mesh(new THREE.BoxGeometry(0.18, 0.7, 0.22), armorMat);\n"
    "            legR.position.set(0.22, 0.4, 0);\n"

    "            // 발판\n"
    "            let footL = new THREE.Mesh(new THREE.BoxGeometry(0.22, 0.1, 0.35), detailGold);\n"
    "            footL.position.set(-0.22, 0.05, -0.05);\n"
    "            let footR = new THREE.Mesh(new THREE.BoxGeometry(0.22, 0.1, 0.35), detailGold);\n"
    "            footR.position.set(0.22, 0.05, -0.05);\n"

    "            bot.add(head, eyeLens, headAntenna, chest, core, shoulderL, shoulderR, armL, armR, waist, legL, legR, footL, footR);\n"

    "            let angle = Math.random() * Math.PI * 2;\n"
    "            let dist = 18 + Math.random() * 20;\n"
    "            bot.position.set(camera.position.x + Math.cos(angle) * dist, 0, camera.position.z + Math.sin(angle) * dist);\n"

    "            scene.add(bot);\n"
    "            bots.push(bot);\n"
    "        }\n"

    "        for (let i = 0; i < 5; i++) createBot();\n"
    "        setInterval(() => { if (bots.length < 7) createBot(); }, 2000);\n"

    "        document.addEventListener('keydown', (e) => { if (keys.hasOwnProperty(e.code)) keys[e.code] = true; });\n"
    "        document.addEventListener('keyup', (e) => { if (keys.hasOwnProperty(e.code)) keys[e.code] = false; });\n"

    "        // -----------------------------------------------------\n"
    "        // 조준(ADS) 및 사격(Shoot) 시스템\n"
    "        // -----------------------------------------------------\n"
    "        let raycaster = new THREE.Raycaster();\n"
    "        let canShoot = true;\n"

    "        // 우클릭 조준(ADS)\n"
    "        document.addEventListener('mousedown', (e) => {\n"
    "            if (e.button === 2) { // 우클릭\n"
    "                isAiming = true;\n"
    "                camera.fov = 28; // 저격 줌인\n"
    "                camera.updateProjectionMatrix();\n"
    "                gun.position.copy(AIM_GUN_POS);\n"
    "            }\n"
    "        });\n"

    "        document.addEventListener('mouseup', (e) => {\n"
    "            if (e.button === 2) { // 우클릭 떼기\n"
    "                isAiming = false;\n"
    "                camera.fov = 65;\n"
    "                camera.updateProjectionMatrix();\n"
    "                gun.position.copy(NORMAL_GUN_POS);\n"
    "            }\n"
    "        });\n"

    "        // 좌클릭 사격\n"
    "        document.addEventListener('click', (e) => {\n"
    "            if (e.button !== 0) return; // 좌클릭만 처리\n"
    "            if (isGameOver) { resetGame(); return; }\n"
    "            if (!canShoot) return;\n"
    "            canShoot = false;\n"

    "            // 반동 모션\n"
    "            let targetZ = isAiming ? -0.1 : -0.2;\n"
    "            gun.position.z += 0.2;\n"
    "            gun.rotation.x = 0.25;\n"
    "            setTimeout(() => {\n"
    "                gun.position.copy(isAiming ? AIM_GUN_POS : NORMAL_GUN_POS);\n"
    "                gun.rotation.x = 0;\n"
    "                canShoot = true;\n"
    "            }, 500);\n"

    "            // 정밀 중앙 레이캐스팅 (화면 중앙 사격)\n"
    "            raycaster.setFromCamera(new THREE.Vector2(0, 0), camera);\n"
    "            let allBotMeshes = [];\n"
    "            bots.forEach(b => {\n"
    "                b.traverse(child => { if (child.isMesh) allBotMeshes.push(child); });\n"
    "            });\n"

    "            let intersects = raycaster.intersectObjects(allBotMeshes);\n"
    "            if (intersects.length > 0) {\n"
    "                let hitMesh = intersects[0].object;\n"
    "                let hitBot = hitMesh.parent;\n"
    "                while (hitBot && !bots.includes(hitBot)) {\n"
    "                    hitBot = hitBot.parent;\n"
    "                }\n"
    "                if (hitBot) {\n"
    "                    scene.remove(hitBot);\n"
    "                    bots = bots.filter(b => b !== hitBot);\n"
    "                    score += 1;\n"
    "                    document.getElementById('score').innerText = score;\n"
    "                    setTimeout(createBot, 500);\n"
    "                }\n"
    "            }\n"
    "        });\n"

    "        function resetGame() {\n"
    "            bots.forEach(b => scene.remove(b));\n"
    "            bots = [];\n"
    "            hp = 100; score = 0; isGameOver = false;\n"
    "            document.getElementById('hp-fill').style.width = '100%';\n"
    "            document.getElementById('score').innerText = '0';\n"
    "            document.getElementById('game-over').style.display = 'none';\n"
    "            camera.position.set(0, PLAYER_HEIGHT, 0.1);\n"
    "            controls.target.set(0, PLAYER_HEIGHT, -10);\n"
    "            for (let i = 0; i < 5; i++) createBot();\n"
    "        }\n"

    "        function animate() {\n"
    "            requestAnimationFrame(animate);\n"
    "            if (isGameOver) return;\n"

    "            // 걸음걸이 속도 조절 (기존 0.2 -> 0.08 로 감축)\n"
    "            let moveSpeed = 0.08;\n"
    "            let forward = new THREE.Vector3();\n"
    "            camera.getWorldDirection(forward);\n"
    "            forward.y = 0; forward.normalize();\n"

    "            let right = new THREE.Vector3().crossVectors(forward, new THREE.Vector3(0, 1, 0)).normalize();\n"
    "            let move = new THREE.Vector3();\n"

    "            if (keys.KeyW) move.add(forward);\n"
    "            if (keys.KeyS) move.sub(forward);\n"
    "            if (keys.KeyD) move.add(right);\n"
    "            if (keys.KeyA) move.sub(right);\n"

    "            if (move.lengthSq() > 0) {\n"
    "                move.normalize().multiplyScalar(moveSpeed);\n"
    "                camera.position.add(move);\n"
    "                controls.target.add(move);\n"
    "            }\n"

    "            camera.position.y = PLAYER_HEIGHT;\n"

    "            // 로봇 이동 및 체력 차감\n"
    "            bots.forEach(bot => {\n"
    "                let dir = new THREE.Vector3().subVectors(camera.position, bot.position);\n"
    "                dir.y = 0;\n"
    "                let dist = dir.length();\n"
    "                dir.normalize();\n"

    "                if (dist > 1.8) {\n"
    "                    bot.position.addScaledVector(dir, 0.045);\n"
    "                } else {\n"
    "                    hp -= 0.3;\n"
    "                    document.getElementById('hp-fill').style.width = Math.max(0, hp) + '%';\n"
    "                    if (hp <= 0) {\n"
    "                        isGameOver = true;\n"
    "                        document.getElementById('game-over').style.display = 'block';\n"
    "                    }\n"
    "                }\n"
    "                bot.lookAt(camera.position.x, 0, camera.position.z);\n"
    "            });\n"

    "            controls.update();\n"
    "            renderer.render(scene, camera);\n"
    "        }\n"
    "        animate();\n"
    "    </script>\n"
    "</body>\n"
    "</html>\n"
)

components.html(game_html, height=720)
